name: Build and Deploy to Laravel backend

on:
  push:
    branches: [master]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install, build, and test
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: Clone Laravel repo
        run: |
          git clone https://github.com/moSa963/chatroom chatroom
          git config user.name "Github action"
          git config user.email "actions@github.com"
        env:
          token: ${{ secrets.CHATROOM_TOKEN }}

      - name: Copy build files into Laravel
        run: |
          rm -rf chatroom/public/assets/*
          cp -r dist/assets/* chatroom/public/assets/

      - name: Rename links in the main html
        run: |
          JS_FILE=$(find dist/assets -name "index-.*.js" -print | xargs -n 1 basename)
          CSS_FILE=$(find dist/assets -name "index-.*.css" -print | xargs -n 1 basename)
          sed -i "s|src=\"/assets/index-.*.js\"|src=\"/assets/${JS_FILE}\"|" chatroom/resources/views/index.blade.php
          sed -i "s|href=\"/assets/index-.*.css\"|href=\"/assets/${CSS_FILE}\"|" chatroom/resources/views/index.blade.php

      - name: Commit and push changes
        run: |
          cd chatroom
          git checkout -B test
          git add .
          git commit -m "Updating react build"
          git push origin test
